image: node:latest

before_script:
  - npm install
  - npm i firebase-tools

# https://gitlab.com/brendan-demo/labwork/homepage/-/blob/c4b1ddd04eb826091de11c4ac5506f4f4770b365/.gitlab-ci.yml
prod-hosting:
  stage: deploy
  script:
    - npm run build
    - npx firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - main
  environment:
    name: production
    url: https://markdowndocs.web.app
