pages:
  stage: deploy
  before_script:
    - npm install
  script:
    - npm run docs:build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
