local_backend: true

backend:
  name: github
  repo: tomhmoses/markdown-docs-example
  branch: main

media_folder: public/img
public_folder: /img

collections:
  - name: 'docs'
    label: 'Docs'
    label_singular: 'Doc'
    folder: 'docs'
    create: true
    slug: '{{slug}}'
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }